//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Authentication.LDAPAuth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LDAPAuth.IAuthenticate")]
    public interface IAuthenticate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticate/Authenticate", ReplyAction="http://tempuri.org/IAuthenticate/AuthenticateResponse")]
        bool Authenticate(string username, string domain, string password, string ldapUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticate/isAuthenticated", ReplyAction="http://tempuri.org/IAuthenticate/isAuthenticatedResponse")]
        bool isAuthenticated(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticateChannel : User_Authentication.LDAPAuth.IAuthenticate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateClient : System.ServiceModel.ClientBase<User_Authentication.LDAPAuth.IAuthenticate>, User_Authentication.LDAPAuth.IAuthenticate {
        
        public AuthenticateClient() {
        }
        
        public AuthenticateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Authenticate(string username, string domain, string password, string ldapUrl) {
            return base.Channel.Authenticate(username, domain, password, ldapUrl);
        }
        
        public bool isAuthenticated(string username) {
            return base.Channel.isAuthenticated(username);
        }
    }
}
